apiVersion: v1
kind: Service
metadata:
  name: demo-http-server-service
  labels:
    app: demo-http-server
spec:
  selector:
    app: demo-http-server
  ports:
  - port: 5000           # Port exposed to external clients
    targetPort: 5000     # Port your container exposes
    protocol: TCP
  type: LoadBalancer