name: End-to-End Test Containerized

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install cloud-provider-kind
        run: |
            go install sigs.k8s.io/cloud-provider-kind@latest
            echo "${HOME}/go/bin" >> $GITHUB_PATH
            cloud-provider-kind  &>cpk.log &

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
            config: kind-config.yaml


      - name: Apply manifests
        run: |
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml

      - name: Wait for server to be ready
        run: |
            kubectl wait --for=condition=ready pod --selector=app=demo-http-server --timeout=120s
            kubectl get svc -owide

      - name: Send GET request and check response
        run: |
          response=$(curl -s http://localhost:5000
          echo "Response: $response"

          if [ "$response" == "Hello there!" ]; then
            echo "The value received is correct"
          else
            echo "Received value is incorrect"
            #exit 1
          fi


      - name: Show logs
        run: |
          cat cpk.log
